# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.


# Project information
site_name: Documentation
site_url:
site_author: SpaGreen Creative
site_description: >-
  Rapiwa provides a powerful and low-cost WhatsApp API for developers to integrate messaging and automation into their applications.

# Repository
repo_name:
repo_url:

# Copyright
copyright: Copyright &copy; 2019 - 2025 SpaGreen Creative

use_directory_urls: false

# Theme configuration
theme:
  name: material
  custom_dir: material/.overrides
  features:
    - navigation.footer
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    - scheme: slate
      primary: blue
      toggle:
        default: true
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: light
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Outfit
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo-color.png

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mermaid2

# Hooks
hooks:
  - material/.overrides/hooks/translations.py

# Extra settings
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/spagreen/
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/spagreencreative
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@spagreen

# Extra CSS/JS (GLightbox included here)
extra_css:
  - assets/custom.css
  - https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js
  - assets/custom.js  # Optional if you have custom JS

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Getting started:
      - Introducing: getting-started.md
  - Device Key:
      - Device Key: api/device-key.md
  - Sessions:
      - Get WhatsApp Session QR Code: api/sessions.md
      - Session User Info: api/session-user-info.md
      - Session Logout: api/session-logout.md
      - Check If A Number Is On WhatsApp: api/verify-whatsapp.md
  - Messages:
      - Send Text Message: api/send-text-message.md
      - Send Image Message: api/send-image-message.md
      - Send Video Message: api/send-video-message.md
      - Send Document Message: api/send-document-message.md
      - Send Audio Message: api/send-audio-message.md
      - Send Location: api/send-location.md
      - Send Quoted Message: api/send-quoted-message.md
      - Delete a Message: api/delete-a-message.md
      - Send Bulk Message: api/send-bulk-message.md
  - Webhooks:
      - Receive Message: api/webhooks/receive-message.md
      - Message Status: api/webhooks/message-status.md
  - N8N:
    - n8n.md
