# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Documentation
site_url:
site_author: SpaGreen Creative
site_description: >-
  VidFlix is your personal streaming platform. Enjoy your favorite movies and TV shows anytime, anywhere.


# Repository
repo_name:
repo_url:

# Copyright
copyright: Copyright &copy; 2019 - 2024 SpaGreen Creative

# Configuration
theme:
  name: material
  custom_dir: material/.overrides
  features:
    - navigation.footer
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: red
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      extra_css:
        - stylesheets/extra.css
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/vidflix_images/favicon.png
  logo: assets/vidflix_images/logo.png


# Plugins
plugins:
  - glightbox:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Hooks
hooks:
  - material/.overrides/hooks/translations.py

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spagreen
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/spagreencreative
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/spagreenbd

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
    #  emoji_generator: !!python/name:material.extensions.emoji.to_svg
    #  emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Introduction: vidflix-usage/getting-started.md
    - Requirements: requirements.md
    - Installation: installation.md
  - Setup:
      - setup/index.md
      - General Setting: vidflix-usage/general.md
      - Admin Settings: vidflix-usage/admin-settings.md
      - Manage Video Type: vidflix-usage/video-type.md  
      - Language Setting: vidflix-usage/language.md
      - Payment Method: vidflix-usage/payout-method.md
      - Email Settings: vidflix-usage/email-settings.md
      - Default Charges: vidflix-usage/default-charge.md
      - Packaging Charges: vidflix-usage/packaging-charge.md

  - Usage:
#      - uses/index.md
      - Merchant:
        - vidflix-usage/create-parcel.md
        - vidflix-usage/add-shop.md
        - vidflix-usage/payout-request.md
        - vidflix-usage/default-payment-account.md
      - Branch Manager:
        - vidflix-usage/pickup-assign.md
      - Delivery Man:
        - vidflix-usage/pickup-delivery.md
  - Utility:
      - vidflix-usage/utility.md

#  - Addon:
#      - Addon:
#          addon/index.md
#  - Changelog:
#      - changelog/index.md

  - User App:
      - App Basics:
         - Recommendation: user-app/recommendation.md
         - Installation: user-app/installation.md
         - Prepare Flutter Environment: user-app/prepare-flutter-environment.md

      - Common Setup:
         - Google Firebase Setup: user-app/google-firebase-setup.md
         - Social Login Setup: user-app/social-login-setup.md
         - Change Api Server Details: user-app/change-api-server-details.md
         - Change App Logo: user-app/change-app-logo.md
         - Change Splash Screen Logo: user-app/change-splash-screen-logo.md

      - Android Setup:
         - Change App Name: user-app/change-app-name.md
         - Change Android Launcher Icon: user-app/change-android-launcher-icon.md
         - Change Android Package Name: user-app/change-android-package-name.md
         - Generate Debug APK: user-app/generate-debug-apk.md
         - Generate Signed APK: user-app/generate-signed-apk.md


      - IOS Setup:
         - Preliminaries: user-app/preliminaries.md
         - Register App On AppStore: user-app/register-app-appstore.md
         - Create Application Record on AppStore : user-app/create-application-record.md
         - Review Xcode project settings:  user-app/review-xcode-project-settings.md
         - Updating the app deployment version: user-app/updating-app-development-version.md
         - Add an app icon: user-app/add-an-app-icon.md
         - Build archive and Submit To AppStore: user-app/build-archive-and-submit.md
         - Update the app build and version numbers: user-app/update-app-build.md
         - Create An App Bundle: user-app/create-app-bundle.md
         - Upload App Bundle To App Store Connect:  user-app/upload-app-bundle.md
         - Updating the app deployment version: user-app/update-app-development-version.md
         - Release your app on TestFlight: user-app/release-on-testflight.md
         - Release your app to the App Store: user-app/release-on-app-store.md
#
  - Smart TV App:
      - App Basics:
         - Recommendation: smart-tv-app/recommendation.md
         - Installation: smart-tv-app/installation.md
         - Prepare Flutter Environment: smart-tv-app/prepare-flutter-environment.md

      - Common Setup:
         - Change Api Server Details: smart-tv-app/change-api-server-details.md
         - Change App Logo: smart-tv-app/change-app-logo.md
         - Change Splash Screen Logo: smart-tv-app/change-splash-screen-logo.md

      - Android Setup:
         - Change App Name: smart-tv-app/change-app-name.md
         - Change Android Launcher Icon: smart-tv-app/change-android-launcher-icon.md
         - Change Android Package Name: smart-tv-app/change-android-package-name.md
         - Generate Debug APK: smart-tv-app/generate-debug-apk.md
         - Generate Signed APK: smart-tv-app/generate-signed-apk.md


      - IOS Setup:
         - Preliminaries: smart-tv-app/preliminaries.md
         - Register App On AppStore: smart-tv-app/register-app-appstore.md
         - Create Application Record on AppStore: smart-tv-app/create-application-record.md
         - Review Xcode project settings: smart-tv-app/review-xcode-project-settings.md
         - Updating the app deployment version: smart-tv-app/updating-app-development-version.md
         - Add an app icon: smart-tv-app/add-an-app-icon.md
         - Build archive and Submit To AppStore: smart-tv-app/build-archive-and-submit.md
         - Update the app build and version numbers: smart-tv-app/update-app-build.md
         - Create An App Bundle: smart-tv-app/create-app-bundle.md
         - Upload App Bundle To App Store Connect: smart-tv-app/upload-app-bundle.md
         - Updating the app deployment version: smart-tv-app/update-app-development-version.md
         - Release your app on TestFlight: smart-tv-app/release-on-testflight.md
         - Release your app to the App Store: smart-tv-app/release-on-app-store.md












